### ISSUE TITLE
Legend does not match the diagram

### ISSUE THREAD

**Issue by alyh** [reactome/browser-curator#1]
In the legend it is:

![legend](http://i.imgur.com/mNAr6Gf.png)

But in the pathway diagram it is:

![diagram](http://i.imgur.com/yl5cg3h.png)

**Comment by fabregat** [comment]
Do you mean the content of the box in the reaction (the two inclined bars) does not match? or the fact there is an extra catalyst (which line ends with a circle on top of the omitted reaction box)?

**Comment by alyh** [comment]
I meant the two slashes, I understand that the circle means a catalyst.

**Comment by fabregat** [comment]
OK, thank you for reporting it.
